version: '3.9'

services:
  api-gateway:
    image: nginx:stable
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - restaurant-service
      - user-service
      - payment-service
      - order-service
      - notification-service

  restaurant-service:
    build:
      context: ./RestaurantService
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - restaurant-db
    environment:
      ConnectionStrings__RestaurantDb: "Server=restaurant-db;Database=restaurantdb;User=yourusername;Password=yourpassword"

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - user-db
    environment:
      ConnectionStrings__UserDb: "Server=user-db;Database=userdb;User=yourusername;Password=yourpassword"

  payment-service:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    depends_on:
      - payment-db
    environment:
      ConnectionStrings__PaymentDb: "Server=payment-db;Database=paymentdb;User=yourusername;Password=yourpassword"

  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "8003:80"
    depends_on:
      - order-db
    environment:
      ConnectionStrings__OrderDb: "Server=order-db;Database=orderdb;User=yourusername;Password=yourpassword"

  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    depends_on:
      - notification-db
    environment:
      ConnectionStrings__NotificationDb: "Server=notification-db;Database=notificationdb;User=yourusername;Password=yourpassword"

  restaurant-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: restaurantdb
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data/restaurant:/var/lib/mysql

  user-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data/user:/var/lib/mysql

  payment-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: paymentdb
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data/payment:/var/lib/mysql

  order-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: orderdb
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3309:3306"
    volumes:
      - ./mysql-data/order:/var/lib/mysql

  notification-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: notificationdb
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3310:3306"
    volumes:
      - ./mysql-data/notification:/var/lib/mysql
