apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    events { }
    http {
    
        server {

            location /restaurant {
                proxy_pass http://restaurant-service;
            }

            location /restaurant/test {
                proxy_pass http://restaurant-service/weatherforecast;
            }

            location /user {
                proxy_pass http://user-service;
            }   
        
            location /user/test {
                proxy_pass http://user-service/weatherforecast;
            }

            location /payment {
                proxy_pass http://payment-service;
            }

            location /payment/test {
                proxy_pass http://payment-service/weatherforecast;
            }

            location /order {
                proxy_pass http://order-service;
            }

            location /order/test {
                proxy_pass http://order-service/weatherforecast;
            }

            location /notification {
                proxy_pass http://notification-service;
            }

            location /notification/test {
                proxy_pass http://notification-service/weatherforecast;
            }
        }
    }
