on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build-and-test-orderservice:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore OrderService/OrderService.csproj
    - name: Build
      run: dotnet build OrderService/OrderService.csproj --no-restore
    - name: Test
      run: dotnet test OFOS.sln --no-build --verbosity normal
